// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNrpcw-6bCJbXBhTBvcLCv5h5qRdSPNhQ',
    appId: '1:825906920690:web:167076299cf112e59b646b',
    messagingSenderId: '825906920690',
    projectId: 'registration-f7976',
    authDomain: 'registration-f7976.firebaseapp.com',
    storageBucket: 'registration-f7976.firebasestorage.app',
    measurementId: 'G-44GHFN20PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8aFoDQOqPPty3KfbltTyvbPOtgv8SAB8',
    appId: '1:825906920690:android:f176b781ce30a6229b646b',
    messagingSenderId: '825906920690',
    projectId: 'registration-f7976',
    storageBucket: 'registration-f7976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwamZ9Bj_LjWbdcYFupL14r-crWmQwDs',
    appId: '1:825906920690:ios:d4f9cef12ebfd3239b646b',
    messagingSenderId: '825906920690',
    projectId: 'registration-f7976',
    storageBucket: 'registration-f7976.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPwamZ9Bj_LjWbdcYFupL14r-crWmQwDs',
    appId: '1:825906920690:ios:d4f9cef12ebfd3239b646b',
    messagingSenderId: '825906920690',
    projectId: 'registration-f7976',
    storageBucket: 'registration-f7976.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNrpcw-6bCJbXBhTBvcLCv5h5qRdSPNhQ',
    appId: '1:825906920690:web:7edfe039fc99d5789b646b',
    messagingSenderId: '825906920690',
    projectId: 'registration-f7976',
    authDomain: 'registration-f7976.firebaseapp.com',
    storageBucket: 'registration-f7976.firebasestorage.app',
    measurementId: 'G-4JEGFZNM7E',
  );
}
